apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: docker.io/shuaishen/backend:07
        ports:
        - containerPort: 5000
        env:
          - name: MONGO_HOST
            value: "192.168.0.16"
          - name: MONGO_PORT
            value: "32001"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 32000
  type: LoadBalancer
